modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Game-Stages"

[[mods]]
modId="gamestages"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.gamestages]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gamestages]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"